// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/proto/todo.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddToDoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Order int64  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Done  bool   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *AddToDoRequest) Reset() {
	*x = AddToDoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_todo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToDoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToDoRequest) ProtoMessage() {}

func (x *AddToDoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToDoRequest.ProtoReflect.Descriptor instead.
func (*AddToDoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_proto_rawDescGZIP(), []int{0}
}

func (x *AddToDoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddToDoRequest) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *AddToDoRequest) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type AddToDoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddToDoResponse) Reset() {
	*x = AddToDoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_todo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToDoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToDoResponse) ProtoMessage() {}

func (x *AddToDoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToDoResponse.ProtoReflect.Descriptor instead.
func (*AddToDoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_proto_rawDescGZIP(), []int{1}
}

func (x *AddToDoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_todo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_proto_rawDescGZIP(), []int{2}
}

type ToDoItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Order int64  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	Done  bool   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *ToDoItem) Reset() {
	*x = ToDoItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_todo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToDoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToDoItem) ProtoMessage() {}

func (x *ToDoItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_todo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToDoItem.ProtoReflect.Descriptor instead.
func (*ToDoItem) Descriptor() ([]byte, []int) {
	return file_api_proto_todo_proto_rawDescGZIP(), []int{3}
}

func (x *ToDoItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ToDoItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ToDoItem) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *ToDoItem) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_api_proto_todo_proto protoreflect.FileDescriptor

var file_api_proto_todo_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x50, 0x0a, 0x0e, 0x41,
	0x64, 0x64, 0x54, 0x6f, 0x44, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x22, 0x21, 0x0a,
	0x0f, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x44, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x5a, 0x0a, 0x08, 0x54, 0x6f, 0x44, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x32, 0x68, 0x0a, 0x04,
	0x74, 0x6f, 0x64, 0x6f, 0x12, 0x32, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x13, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x44, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x44, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x49, 0x74,
	0x65, 0x6d, 0x22, 0x00, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_todo_proto_rawDescOnce sync.Once
	file_api_proto_todo_proto_rawDescData = file_api_proto_todo_proto_rawDesc
)

func file_api_proto_todo_proto_rawDescGZIP() []byte {
	file_api_proto_todo_proto_rawDescOnce.Do(func() {
		file_api_proto_todo_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_todo_proto_rawDescData)
	})
	return file_api_proto_todo_proto_rawDescData
}

var file_api_proto_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_todo_proto_goTypes = []interface{}{
	(*AddToDoRequest)(nil),  // 0: api.AddToDoRequest
	(*AddToDoResponse)(nil), // 1: api.AddToDoResponse
	(*EmptyMessage)(nil),    // 2: api.EmptyMessage
	(*ToDoItem)(nil),        // 3: api.ToDoItem
}
var file_api_proto_todo_proto_depIdxs = []int32{
	0, // 0: api.todo.Add:input_type -> api.AddToDoRequest
	2, // 1: api.todo.List:input_type -> api.EmptyMessage
	1, // 2: api.todo.Add:output_type -> api.AddToDoResponse
	3, // 3: api.todo.List:output_type -> api.ToDoItem
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_todo_proto_init() }
func file_api_proto_todo_proto_init() {
	if File_api_proto_todo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_todo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToDoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_todo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToDoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_todo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_todo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToDoItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_todo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_todo_proto_goTypes,
		DependencyIndexes: file_api_proto_todo_proto_depIdxs,
		MessageInfos:      file_api_proto_todo_proto_msgTypes,
	}.Build()
	File_api_proto_todo_proto = out.File
	file_api_proto_todo_proto_rawDesc = nil
	file_api_proto_todo_proto_goTypes = nil
	file_api_proto_todo_proto_depIdxs = nil
}
